const { test, expect } = require("@playwright/test")
const fs = require("node:fs/promises")
const os = require("node:os")
const path = require("node:path")
const PouchDB = require("pouchdb")
const expressPouchDB = require("express-pouchdb")
const { launchApp, closeApp, startPageServer, seedLocalSource, openSettingsSection, showAllStories } = require("./electron-harness")
const stories = require("../shared/story-fixture")
const local = require("../shared/local-addon-fixture")
const { installAiAddon } = require("../shared/ai-addon-ui")
const { addonOverview, addonSettings } = require("../shared/addon-settings-ui")

async function syncWith(page, url) {
  await openSettingsSection(page, "sync", "#couch_input")
  await page.getByTestId("sync-url").fill(url)
  await page.getByTestId("save-sync").click()
  await expect(page.getByTestId("sync-status")).toHaveAttribute("data-state", "up-to-date", { timeout: 20000 })
}

test("two Electron clients sync an imported package and AI token after one vault unlock", async () => {
  test.setTimeout(120000)
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "once-vault-http-"))
  const Db = PouchDB.defaults({ prefix: directory + path.sep })
  const remote = new Db("once")
  await remote.info()
  const api = expressPouchDB(Db, { mode: "minimumForPouchDB", inMemoryConfig: true })
  const http = await new Promise(resolve => { const server = api.listen(0, "127.0.0.1", () => resolve(server)) })
  const syncUrl = `http://127.0.0.1:${http.address().port}/once`
  const feed = await startPageServer()
  const first = await launchApp({ env: { ONCE_ELECTRON_DISABLE_NETWORK_FETCH: "0" } })
  let second
  try {
    const href = stories.storyUrls(feed.origin).alpha
    const page = first.window
    await seedLocalSource(page, stories.sourceLine(feed.origin), href)
    await openSettingsSection(page, "addons", "#addons_area")
    await installAiAddon(page, feed.origin)
    await local.importZip(page)
    await expect(page.locator("#addon_overview")).toBeVisible()
    await expect(page.locator(".addon_list_row")).toHaveCount(2)
    await syncWith(page, syncUrl)
    await openSettingsSection(page, "addons", "#addons_area")
    await addonOverview(page)
    const controls = page.locator("#addon_vault_controls")
    await controls.getByTestId("addon-vault-secret").fill("test passphrase for two devices")
    await controls.getByLabel("Confirm sync passphrase").fill("test passphrase for two devices")
    await controls.getByLabel("Name this device").fill("Test laptop")
    await controls.getByRole("button", { name: "Enable encrypted addon sync" }).click()
    await expect(controls.getByTestId("addon-vault-status")).toContainText("Ready", { timeout: 10000 })
    await expect(controls.getByTestId("addon-vault-recovery-key")).toHaveValue(/^[a-f0-9]{64}$/)
    await controls.getByRole("button", { name: "I saved my recovery key" }).click()
    await expect.poll(async () => (await remote.get("addon_vault").catch(() => null))?.list?.version).toBe(1)
    expect(JSON.stringify(await remote.allDocs({ include_docs: true }))).not.toContain("fixture-token")

    second = await launchApp({ env: { ONCE_ELECTRON_DISABLE_NETWORK_FETCH: "0" } })
    const other = second.window
    await syncWith(other, syncUrl)
    await openSettingsSection(other, "addons", "#addons_area")
    await addonOverview(other)
    const unlock = other.locator("#addon_vault_controls")
    await expect(unlock.getByTestId("addon-vault-status")).toContainText("Unlock")
    await expect(other.locator(".addon_list_row")).toHaveCount(0)
    await unlock.getByTestId("addon-vault-secret").fill("test passphrase for two devices")
    await unlock.getByLabel("Name this device").fill("Test phone")
    await unlock.getByRole("button", { name: "Unlock synced connections" }).click()
    await expect(unlock.getByTestId("addon-vault-status")).toContainText("Ready")
    await expect(other.locator(".addon_list_row")).toHaveCount(2)
    await addonSettings(other, "what-wait-who-why")
    const token = other.getByTestId("addon-option-what-wait-who-why-compatibleToken")
    await expect(token).toHaveValue("")
    await expect(token.locator("..").getByRole("status")).toHaveText("Token saved · Encrypted sync")
    await showAllStories(other)
    await other.getByTestId("reload-stories").click()
    const row = other.locator(`[data-href="${href}"]`)
    await expect(row.locator('[data-addon-badge="ready"]')).toHaveText("Local package ready")
    await row.locator('[data-addon-tray-button="addon:what-wait-who-why/assistant"]').click()
    await expect(row.getByTestId("addon-tray")).toContainText("ExampleApp is software")
    await openSettingsSection(other, "addons", "#addons_area")
    await addonOverview(other)
    await unlock.getByRole("button", { name: "Lock and forget on this device" }).click()
    await expect(unlock.getByTestId("addon-vault-status")).toContainText("Unlock")
    await expect(other.locator(".addon_list_row")).toHaveCount(0)
    await unlock.screenshot({ path: "artifacts/addon-vault/locked-electron.png" })
    await other.reload()
    await other.waitForSelector('body[data-once-ready="true"]')
    await openSettingsSection(other, "addons", "#addons_area")
    await expect(other.getByTestId("addon-vault-status")).toContainText("Unlock")
  } finally {
    if (second) await closeApp(second.electronApp, second.userData)
    await closeApp(first.electronApp, first.userData)
    await feed.close()
    http.closeAllConnections()
    await new Promise(resolve => http.close(resolve))
    await remote.destroy()
  }
})
