const { test, expect } = require("@playwright/test")
const { launchApp, closeApp, openSettingsSection } = require("./electron-harness")
const { addonAdvanced, addonOverview, addonSettings, addonImport } = require("../shared/addon-settings-ui")

test("addon overview, isolated settings, import and advanced pages work with keyboard and narrow panels", async () => {
  const { electronApp, userData, window } = await launchApp()
  try {
    await openSettingsSection(window, "addons")
    await expect(window.getByTestId("addons")).toBeHidden()
    await expect(window.getByTestId("addon-url")).toBeHidden()
    await expect(window.locator("#addon_overview")).toContainText("No addons yet")
    await addonAdvanced(window)
    const manifests = ["First", "Second"].map(name => ({
      protocol: 1, id: name.toLowerCase(), name, version: "1.0.0", contributions: [],
      settings: { type: "object", properties: {
        prompt: { type: "string", label: "Prompt", format: "multiline", default: `${name} default` }
      } }
    }))
    await window.getByTestId("addons").fill(JSON.stringify(manifests))
    await window.getByTestId("save-addons").click()
    await addonOverview(window)
    await expect(window.locator(".addon_list_row")).toHaveCount(2)
    const first = window.locator('.addon_list_row[data-addon-id="first"]')
    await first.focus()
    await first.press("Enter")
    const prompt = window.getByTestId("addon-option-first-prompt")
    await expect(prompt).toBeVisible()
    await expect(window.getByTestId("addon-option-second-prompt")).toBeHidden()
    await expect(window.locator("#settings_panel .settings_title")).toHaveText("First")
    await prompt.fill("My edited prompt")
    await prompt.evaluate(element => { element.dataset.retentionMarker = "same-node" })
    await addonOverview(window)
    await expect(first).toBeFocused()
    await addonSettings(window, "second")
    await expect(window.getByTestId("addon-option-second-prompt")).toHaveValue("Second default")
    await addonSettings(window, "first")
    await expect(prompt).toHaveValue("My edited prompt")
    await expect(prompt).toHaveAttribute("data-retention-marker", "same-node")
    await window.getByRole("button", { name: "Disable", exact: true }).click()
    await expect(prompt).toBeEnabled()
    await window.locator('#addon_installed [data-addon-id="first"]').getByRole("button", { name: "Remove", exact: true }).click()
    await expect(window.locator("#addon_overview")).toBeVisible()
    await expect(window.locator(".addon_list_row")).toHaveCount(1)
    await addonImport(window)
    await expect(window.getByTestId("import-addon-zip")).toBeVisible()
    await expect(window.getByTestId("addon-url")).toBeVisible()
    await expect(window.getByTestId("addons")).toBeHidden()
    await window.locator("#addon_install_settings").evaluate(element => { element.style.width = "310px" })
    expect(await window.locator("#addon_install_settings").evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await addonSettings(window, "second")
    expect(await window.locator("#addon_install_settings").evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await addonAdvanced(window)
    await expect(window.getByTestId("addons")).toBeVisible()
    await window.getByTestId("addons").fill("{invalid")
    await window.getByTestId("save-addons").click()
    await expect(window.locator("#addon_advanced .settings_status")).toContainText("Could not save")
    await expect(window.getByTestId("addons")).toHaveValue("{invalid")
  } finally { await closeApp(electronApp, userData) }
})
