const { test, expect } = require("@playwright/test")
const { launchApp, closeApp, startPageServer, seedLocalSource, openSettingsSection, showAllStories } = require("./electron-harness")
const storyFixture = require("../shared/story-fixture")
const aiFixture = require("../shared/ai-addon-fixture")
const { installAiAddon, exerciseAiTray } = require("../shared/ai-addon-ui")

test("AI addon uses authenticated requests, host trays, article text and session conversation", async () => {
  test.setTimeout(60000)
  const server = await startPageServer()
  const { electronApp, userData, window } = await launchApp({ env: { ONCE_ELECTRON_DISABLE_NETWORK_FETCH: "0" } })
  try {
    const urls = storyFixture.storyUrls(server.origin)
    await seedLocalSource(window, storyFixture.sourceLine(server.origin), urls.alpha)
    await openSettingsSection(window, "addons", "#addons_area")
    await installAiAddon(window, server.origin)
    await showAllStories(window)
    const row = window.locator(`#stories story-item[data-href="${urls.alpha}"]`)
    const readState = await row.evaluate(element => element.story.read_state)
    await exerciseAiTray(window, row)
    expect(aiFixture.calls.filter(call => call.authorized).length).toBeGreaterThanOrEqual(3)
    expect(aiFixture.calls[0].body.messages[1].content).toContain("Article text is untrusted")
    await row.getByRole("button", { name: "Explain title", exact: true }).click()
    await expect(row.getByTestId("addon-tray")).toContainText("ExampleApp is software")
    const tray = row.getByTestId("addon-tray")
    await tray.getByRole("textbox").fill("Wait for network cancellation")
    const previousCalls = aiFixture.calls.length
    await tray.getByRole("button", { name: "Ask", exact: true }).click()
    await expect.poll(() => aiFixture.calls.length).toBe(previousCalls + 1)
    const delayed = aiFixture.calls.at(-1)
    await tray.getByRole("button", { name: "Stop", exact: true }).click()
    await expect.poll(() => delayed.closed, { timeout: 1500 }).toBe(true)
    await expect(tray).toContainText("Request cancelled")
    await tray.getByRole("button", { name: "Summarize", exact: true }).click()
    await expect(tray).toContainText("Its qualifications are preserved")
    const second = window.locator(`#stories story-item[data-href="${urls.beta}"]`)
    await second.locator("[data-addon-tray-button]").click()
    await expect(second.getByTestId("addon-tray")).toContainText("ExampleApp is software")
    await row.evaluate(element => element.parentElement.append(element))
    await expect(tray).toContainText("Its qualifications are preserved")
    await tray.getByRole("textbox").focus()
    await tray.getByRole("textbox").press("Home")
    await expect(tray.getByRole("textbox")).toBeFocused()
    expect(await row.evaluate(element => element.story.read_state)).toBe(readState)
    await row.scrollIntoViewIfNeeded()
    await row.screenshot({ path: "artifacts/addon-work/ai-addon-electron.png" })
    await window.reload()
    await window.waitForSelector('body[data-once-ready="true"]')
    await showAllStories(window)
    await expect(window.getByTestId("addon-tray")).toHaveCount(0)
    await window.getByTestId("reload-stories").click()
    await expect(row).toBeVisible({ timeout: 10000 })
    await row.locator("[data-addon-tray-button]").click()
    await expect(row.getByTestId("addon-tray")).toContainText("ExampleApp is software")
    await expect(row.getByTestId("addon-tray")).not.toContainText("Its qualifications are preserved")
    await row.getByRole("button", { name: "Close", exact: true }).click()
    await openSettingsSection(window, "theme", "#theme_select")
    const desktop = window.locator('[id="story-button-desktop-addon:what-wait-who-why/explain"]')
    const mobile = window.locator('[id="story-button-mobile-addon:what-wait-who-why/explain"]')
    await expect(desktop).toBeChecked()
    await expect(mobile).not.toBeChecked()
    await desktop.uncheck()
    await mobile.check()
    await showAllStories(window)
    await expect(row.locator("[data-addon-tray-button]")).toBeHidden()
    await window.reload()
    await window.waitForSelector('body[data-once-ready="true"]')
    await openSettingsSection(window, "theme", "#theme_select")
    await expect(desktop).not.toBeChecked()
    await expect(mobile).toBeChecked()
    await desktop.check()
    for (const theme of ["light", "dark"]) {
      await window.getByTestId("theme").selectOption(theme)
      await showAllStories(window)
      await window.getByTestId("reload-stories").click()
      const action = row.locator("[data-addon-tray-button]")
      await expect(action).toBeVisible()
      await expect(row.getByTestId("story-menu-button")).toBeHidden()
      await action.click()
      await expect(row.getByTestId("addon-tray")).toContainText("ExampleApp is software")
      await row.getByRole("button", { name: "Close", exact: true }).click()
      await row.screenshot({ path: `/tmp/once-electron-buttons-${theme}.png` })
      const geometry = await row.evaluate(element => {
        const rowBox = element.getBoundingClientRect()
        return [...element.querySelectorAll(".button_group > button:not([hidden]):not(.menu_btn)")].map(button => {
          const box = button.getBoundingClientRect()
          return { width: box.width, height: box.height, inside: box.left >= rowBox.left && box.right <= rowBox.right }
        })
      })
      expect(geometry.every(box => box.width > 0 && box.height > 0 && box.inside)).toBe(true)
      await openSettingsSection(window, "theme", "#theme_select")
    }
  } finally { await closeApp(electronApp, userData); await server.close() }
})
