const { test, expect } = require("@playwright/test")
const { seedFixtureStories } = require("./helpers/stories")
const { openSettingsSection } = require("./helpers/settings")
const { reloadMobileApp } = require("./helpers/mobile-app")

test("domain taps open stories by default and domain search is an optional persistent setting", async ({ page }) => {
  const story = await seedFixtureStories(page)
  const domain = story.locator(".hostname")
  await expect(domain).toHaveAttribute("href", await story.getByTestId("story-title").getAttribute("href"))
  await domain.tap()
  await expect(page.locator("#reading_content")).toHaveAttribute("data-mode", "browser")
  await expect(page.locator("#reading_content")).toBeVisible()
  await page.locator("#reading_story_menu").tap()
  await page.getByTestId("story-menu-search-domain").tap()
  await expect(page.locator("#searchfield")).toHaveValue("domain:127.0.0.1")

  await openSettingsSection(page, "theme")
  const toggle = page.getByRole("checkbox", { name: "Search by tapping domain names" })
  await expect(toggle).not.toBeChecked()
  await toggle.check()
  await reloadMobileApp(page)
  await openSettingsSection(page, "theme")
  await expect(toggle).toBeChecked()
  for (const theme of ["light", "dark"]) {
    await page.getByTestId("theme").selectOption(theme)
    await toggle.scrollIntoViewIfNeeded()
    const geometry = await toggle.evaluate(input => {
      const box = input.getBoundingClientRect()
      const section = input.closest("section").getBoundingClientRect()
      return { width: box.width, right: box.right, sectionRight: section.right,
        overflow: document.documentElement.scrollWidth > innerWidth }
    })
    expect(geometry.width).toBeGreaterThan(0)
    expect(geometry.right).toBeLessThanOrEqual(geometry.sectionRight)
    expect(geometry.overflow).toBe(false)
  }
  await page.getByTestId("stories-menu").tap()
  await page.getByTestId("reload-stories").tap()
  await expect(domain).toHaveAttribute("href", "search:domain:127.0.0.1")
  await domain.tap()
  await expect(page.locator("#searchfield")).toHaveValue("domain:127.0.0.1")
  await openSettingsSection(page, "theme")
  await toggle.uncheck()
  await expect(domain).toHaveAttribute("href", await story.getByTestId("story-title").getAttribute("href"))
  await reloadMobileApp(page)
  await openSettingsSection(page, "theme")
  await expect(toggle).not.toBeChecked()
  await page.getByTestId("stories-menu").tap()
  await page.getByTestId("reload-stories").tap()
  await domain.tap()
  await expect(page.locator("#reading_content")).toBeVisible()
})
