const { test, expect } = require("@playwright/test")
const { gotoMobileApp, reloadMobileApp, triggerMobileBack } = require("./helpers/mobile-app")
const { seedFixtureStories, openStoryMenu } = require("./helpers/stories")

const switcher = page => page.locator("#reading_tabs_dialog")
const openTabs = page => page.locator("#reading_tabs").click()
const newTab = async page => {
  await openTabs(page)
  await switcher(page).getByRole("button", { name: "New tab", exact: true }).click()
}

test("background story tabs preserve feed selection; foreground tabs append and ordinary taps reuse", async ({ page }) => {
  const story = await seedFixtureStories(page)
  await openStoryMenu(page, story)
  await page.getByTestId("story-menu-open-background-tab").click()
  await expect(page.locator("#stories_panel")).toBeVisible()
  await openStoryMenu(page, story)
  await page.getByTestId("story-menu-open-new-tab").click()
  await expect(page.locator("#reading_tabs")).toHaveText("2")
  await triggerMobileBack(page)
  await expect(page.locator("#stories_panel")).toBeVisible()
  await story.getByTestId("story-title").click()
  await expect(page.locator("#reading_tabs")).toHaveText("2")
  await openTabs(page)
  await expect(switcher(page).locator(".reading_tab_row")).toHaveCount(2)
})

test("empty tabs, close selection, close-all confirmation, undo and restart restoration", async ({ page }) => {
  await gotoMobileApp(page)
  await page.getByRole("button", { name: "Reading", exact: true }).click()
  await newTab(page)
  await expect(page.locator("#reading_url")).toBeFocused()
  await page.locator("#reading_url").fill("https://first.example/")
  await page.locator("#reading_url").press("Enter")
  await newTab(page)
  await expect(page.locator("#reading_url")).toHaveValue("")
  await page.locator("#reading_url").fill("https://second.example/")
  await page.locator("#reading_url").press("Enter")
  await openTabs(page)
  await switcher(page).getByRole("button", { name: "Close tab: https://second.example/", exact: true }).click()
  await switcher(page).getByRole("button", { name: "Done", exact: true }).click()
  await expect(page.locator("#reading_url")).toHaveValue("https://first.example/")
  await openTabs(page)
  await switcher(page).getByRole("button", { name: "Undo close", exact: true }).click()
  await expect(switcher(page).locator(".reading_tab_row")).toHaveCount(2)
  await switcher(page).getByRole("button", { name: "Close all", exact: true }).click()
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await expect(switcher(page).locator(".reading_tab_row")).toHaveCount(2)
  await switcher(page).getByRole("button", { name: "Close all", exact: true }).click()
  await page.getByRole("button", { name: "Close all tabs", exact: true }).click()
  await expect(switcher(page).getByText("No open tabs")).toBeVisible()
  await switcher(page).getByRole("button", { name: "Undo close", exact: true }).click()
  await switcher(page).getByRole("button", { name: "Done", exact: true }).click()
  await reloadMobileApp(page)
  await page.getByRole("button", { name: "Reading", exact: true }).click()
  await expect(page.locator("#reading_url")).toHaveValue("https://second.example/")
  await openTabs(page)
  await expect(switcher(page).locator(".reading_tab_row")).toHaveCount(2)
  await expect(switcher(page).getByRole("button", { name: "Undo close", exact: true })).toBeDisabled()
  await triggerMobileBack(page)
  await expect(switcher(page)).not.toBeVisible()
  await expect(page.locator("#reading_tabs")).toBeFocused()
})

test("reader documents survive tab switches and failures belong to their tab", async ({ page }) => {
  const story = await seedFixtureStories(page)
  await openStoryMenu(page, story)
  await page.getByTestId("story-menu-open-reader").click()
  const frame = () => page.locator(".once-reader-host:not([hidden]) iframe").contentFrame()
  await expect(frame().locator("article").first()).toBeVisible()
  await frame().locator("body").evaluate(body => { body.dataset.retained = "original-document" })
  await newTab(page)
  await page.locator("#reading_url").fill(new URL("/fixtures/article.html?second", page.url()).href)
  await page.locator("#reading_url").press("Enter")
  await page.evaluate(() => window.__onceE2E__.failReading("Only the second tab failed"))
  await expect(page.locator("#reading_error")).toBeVisible()
  await openTabs(page)
  await switcher(page).locator('[data-action="select"]').first().click()
  await expect(page.locator("#reading_error")).toBeHidden()
  await expect(frame().locator("body")).toHaveAttribute("data-retained", "original-document")
  await expect(page.locator("#reading_content")).toHaveAttribute("data-load-state", "ready")
  await openTabs(page)
  await switcher(page).locator('[data-action="select"]').last().click()
  await expect(page.locator("#reading_error")).toContainText("Only the second tab failed")
})

test("tab dialog fits phone and tablet viewports in both themes", async ({ page }) => {
  const { openSettingsSection } = require("./helpers/settings")
  await gotoMobileApp(page)
  await page.getByRole("button", { name: "Reading", exact: true }).click()
  await newTab(page)
  await page.locator("#reading_url").fill("https://example.test/a-long-article-address-for-tab-layout")
  await page.locator("#reading_url").press("Enter")
  await newTab(page)
  for (const theme of ["light", "dark"]) {
    await openSettingsSection(page, "theme")
    await page.locator("#theme_select").selectOption(theme)
    await page.getByRole("button", { name: "Reading", exact: true }).click()
    await openTabs(page)
    for (const viewport of [{ width: 320, height: 720 }, { width: 412, height: 915 }, { width: 915, height: 412 }, { width: 768, height: 1024 }]) {
      await page.setViewportSize(viewport)
      const geometry = await switcher(page).evaluate(dialog => {
        const box = dialog.getBoundingClientRect()
        const rows = dialog.querySelector(".reading_tab_rows").getBoundingClientRect()
        const footer = dialog.querySelector("footer").getBoundingClientRect()
        return { width: box.width, height: box.height, right: box.right, top: box.top, rowsBottom: rows.bottom, footerTop: footer.top, footerBottom: footer.bottom, overflow: document.documentElement.scrollWidth > innerWidth }
      })
      expect(geometry.height).toBe(viewport.height)
      expect(geometry.right).toBeLessThanOrEqual(viewport.width)
      expect(geometry.top).toBe(0)
      expect(geometry.rowsBottom).toBeLessThanOrEqual(geometry.footerTop)
      expect(geometry.footerBottom).toBeLessThanOrEqual(viewport.height)
      expect(geometry.overflow).toBe(false)
      if (viewport.width === 412) await page.screenshot({ path: `/tmp/once-tabs-${theme}.png` })
    }
    await switcher(page).getByRole("button", { name: "Done", exact: true }).click()
    await expect(page.locator("#reading_tabs")).toBeFocused()
  }
})
