const { test, expect } = require("@playwright/test")
const { seedFixtureStories } = require("./helpers/stories")
const { openSettingsSection } = require("./helpers/settings")
const { triggerMobileBack } = require("./helpers/mobile-app")
const { installAiAddon } = require("../shared/ai-addon-ui")

for (const mode of ["reader", "browser"]) {
  test(`Reading ${mode} shows and dismisses the shared WWWW conversation`, async ({ page }) => {
    const story = await seedFixtureStories(page)
    await openSettingsSection(page, "addons")
    await installAiAddon(page, new URL(page.url()).origin)
    await page.getByTestId("stories-menu").click()
    if (mode === "reader") {
      await story.getByTestId("story-menu-button").click()
      await page.getByTestId("story-menu-open-reader").click()
    } else await story.locator("a.title").click()
    await expect(page.locator("#reading_content")).toHaveAttribute("data-mode", mode)
    const host = page.locator("#reading_addon_trays")
    for (const theme of ["light", "dark"]) {
      await page.evaluate(theme => { document.body.dataset.theme = theme }, theme)
      await page.locator("#reading_story_menu").click()
      await page.getByTestId("story-menu").getByText("What? Wait, who, why?", { exact: true }).click()
      await expect(host).toBeVisible()
      await expect(host).toContainText("ExampleApp is software", { timeout: 20000 })
      await host.getByRole("button", { name: "Summarize", exact: true }).click()
      await expect(host).toContainText("Its qualifications are preserved")
      await host.getByRole("textbox").fill("Who uses it?")
      await host.getByRole("button", { name: "Ask", exact: true }).click()
      await expect(host).toContainText("Developers use it")
      const bounds = await host.boundingBox()
      const content = await page.locator("#reading_content").boundingBox()
      expect(bounds).toEqual(content)
      expect(await host.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
      await page.screenshot({ path: `/tmp/once-reading-${mode}-tray-${theme}.png` })
      await triggerMobileBack(page)
      await expect(host).toBeHidden()
      await expect(page.locator("#reading_content")).toBeVisible()
    }
    await page.locator("#reading_story_menu").click()
    await page.getByTestId("story-menu").getByText("What? Wait, who, why?", { exact: true }).click()
    await expect(host).toContainText("Developers use it")
    await page.getByTestId("stories-menu").click()
    await expect(story.getByTestId("addon-tray")).toContainText("Developers use it")
    await story.getByRole("button", { name: "Close", exact: true }).click()
    await page.getByTestId("reading-menu").click()
    await expect(host).toBeHidden()
  })
}
