const { test, expect } = require("@playwright/test")
const { reloadMobileApp } = require("./helpers/mobile-app")
const { seedFixtureStories } = require("./helpers/stories")
const { openSettingsSection } = require("./helpers/settings")
const { installAiAddon, exerciseAiTray } = require("../shared/ai-addon-ui")

test("story buttons default to the menu and have independent persistent platform choices", async ({ page }) => {
  const story = await seedFixtureStories(page)
  await openSettingsSection(page, "addons")
  await installAiAddon(page, new URL(page.url()).origin)
  await page.getByTestId("stories-menu").click()
  const action = story.locator(".addon_btn")
  await expect(action).toBeHidden()
  await story.getByTestId("story-menu-button").click()
  await page.getByTestId("story-menu").getByText("What? Wait, who, why?", { exact: true }).click()
  await expect(story.getByTestId("addon-tray")).toContainText("ExampleApp is software", { timeout: 20000 })
  await story.getByRole("button", { name: "Close", exact: true }).click()
  await openSettingsSection(page, "theme")
  const mobile = page.locator('[id="story-button-mobile-addon:what-wait-who-why/explain"]')
  const desktop = page.locator('[id="story-button-desktop-addon:what-wait-who-why/explain"]')
  await expect(mobile).not.toBeChecked()
  await expect(desktop).toBeChecked()
  await mobile.check()
  await desktop.uncheck()
  for (const theme of ["light", "dark"]) {
    await page.getByTestId("theme").selectOption(theme)
    await page.getByTestId("stories-menu").click()
    await expect(action).toBeVisible()
    const a = await action.boundingBox()
    const m = await story.getByTestId("story-menu-button").boundingBox()
    expect(a.width).toBe(m.width)
    expect(a.height).toBe(m.height)
    expect(a.y).toBe(m.y)
    expect(a.x + a.width).toBeLessThan(m.x)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `/tmp/once-story-buttons-${theme}.png` })
    await openSettingsSection(page, "theme")
  }
  await page.screenshot({ path: "/tmp/once-story-button-settings.png" })
  await reloadMobileApp(page)
  await page.getByTestId("stories-menu").click()
  await page.getByTestId("reload-stories").click()
  await expect(action).toBeVisible()
  await exerciseAiTray(page, story)
  await openSettingsSection(page, "theme")
  for (const input of await page.locator('[id^="story-button-mobile-"]').all()) await input.check()
  await page.getByTestId("stories-menu").click()
  await page.setViewportSize({ width: 320, height: 740 })
  await story.getByTestId("story-bookmark").click()
  await expect(story).toHaveClass(/stared/)
  const geometry = await story.evaluate(row => {
    const data = row.querySelector(".data").getBoundingClientRect()
    const group = row.querySelector(".button_group").getBoundingClientRect()
    return { textWidth: data.width, actionsTop: group.top, textBottom: data.bottom,
      boxes: [...row.querySelectorAll(".button_group > button:not([hidden])")].map(button => {
        const rect = button.getBoundingClientRect()
        return { width: rect.width, height: rect.height, right: rect.right }
      }) }
  })
  expect(geometry.textWidth).toBeGreaterThan(280)
  expect(geometry.actionsTop).toBeGreaterThanOrEqual(geometry.textBottom)
  for (const box of geometry.boxes) {
    expect(box.width).toBe(28)
    expect(box.height).toBe(28)
    expect(box.right).toBeLessThanOrEqual(320)
  }
  const last = await story.getByTestId("story-menu-button").boundingBox()
  expect(last.x + last.width).toBe(Math.max(...geometry.boxes.map(box => box.right)))
  await page.screenshot({ path: "/tmp/once-story-buttons-narrow.png" })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.evaluate(() => {
    document.querySelector('link[href*="mobile.css"]').remove()
    document.body.dataset.platform = "electron"
    document.querySelectorAll("story-item").forEach(row => row.update_complete_story_el())
  })
  await expect(action).toBeHidden()
  await page.screenshot({ path: "/tmp/once-story-buttons-desktop.png" })
})
