const { test, expect } = require("@playwright/test")
const { seedFixtureStories, openStoryMenu } = require("./helpers/stories")
const { openSettingsSection } = require("./helpers/settings")

for (const theme of ["light", "dark"]) {
  test(`matching story survives redirects and fragment jumps in ${theme} theme`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 440, height: 956 })
    const story = await seedFixtureStories(page)
    const original = await story.getAttribute("data-href")
    await openSettingsSection(page, "theme")
    await page.getByTestId("theme").selectOption(theme)
    await page.getByTestId("stories-menu").click()
    await openStoryMenu(page, story)
    await page.getByTestId("story-menu-open").click()
    const card = page.getByTestId("reading-current-card")
    await expect(card).toBeVisible()
    const redirected = `${original}/`
    await page.evaluate(url => window.__onceE2E__.finishReading(url), redirected)
    await expect(card).toBeVisible()
    await expect(page.getByTestId("reading-url-input")).toHaveValue(redirected)
    await page.evaluate(url => window.__onceE2E__.finishReading(url), redirected + "#heading")
    await expect(card).toBeVisible()
    const bounds = await card.boundingBox()
    expect(bounds.width).toBeLessThanOrEqual(440)
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(await card.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`matched-redirect-${theme}.png`) })
    await page.locator("#reading_story_collapse").click()
    await expect(card).toHaveClass(/reading_story_collapsed/)
    await page.evaluate(url => window.__onceE2E__.finishReading(url, 404), redirected)
    await expect(card).toBeHidden()
    await page.evaluate(url => window.__onceE2E__.finishReading(url, 200), redirected)
    await expect(card).toBeVisible()
    await page.evaluate(() => window.__onceE2E__.finishReading("https://example.test/404", 200))
    await expect(card).toBeHidden()
    await page.evaluate(url => window.__onceE2E__.finishReading(url, 200), redirected)
    await expect(card).toBeVisible()
    await page.evaluate(() => window.__onceE2E__.failReading("The request failed"))
    await expect(card).toBeHidden()
    const address = page.getByTestId("reading-url-input")
    await address.fill("https://example.test/unrelated")
    await page.getByTestId("reading-url-action").click()
    await expect(card).toBeHidden()
  })
}
